#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

GENERATED_DIR="packages/cli/src/generated"
GIT_COMMIT_FILE="$GENERATED_DIR/git-commit.ts"
GIT_COMMIT_INFO="N/A"

mkdir -p "$GENERATED_DIR"

if command -v git &> /dev/null && git rev-parse --is-inside-work-tree &> /dev/null; then
    GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "")
    if [ -n "$GIT_HASH" ]; then
        GIT_COMMIT_INFO="$GIT_HASH"
        if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
            GIT_COMMIT_INFO="$GIT_HASH (local modifications)"
        fi
    fi
fi

cat <<EOL > "$GIT_COMMIT_FILE"
/**
 * @license
 * Copyright $(date +%Y) Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// This file is auto-generated by the build script (scripts/build.sh)
// Do not edit this file manually.
export const GIT_COMMIT_INFO = '$GIT_COMMIT_INFO';
EOL
